on:
  workflow_call:
    inputs:
      npmPackFilename:
        description: The name of the packed npm package (the gzipped tarball).
        type: string
        required: true
      semVer:
        description: The SemVer version number of this build (automated with GitVersion).
        type: string
        required: true
    secrets:
      NPM_TOKEN:
        description: Credentials token for publishing to the npm registry.
        required: true

jobs:
  NpmPublish:
    # Workflow names appear as `origin name / workflow name`, so use `npm` for something like `Publish / npm`
    name: npm
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.npmPackFilename }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Publish
        run: npm publish ${{ inputs.npmPackFilename }} --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag
        run: |
          git tag v${{ inputs.semVer }}
          git push origin tag v${{ inputs.semVer }}
